### ISSUE TITLE
App crash in Qualaroo sdk 1.4.4 (report from Google Play)

### ISSUE THREAD

**Issue by chapp-hk** [qualaroo/AndroidSDK#6]
When the app initialize Qualaroo in Application class

Caused by: java.lang.ArrayIndexOutOfBoundsException: 
  at okio.b.a (Base64.java:137)
  at okio.b.a (Base64.java:125)
  at okio.ByteString.b (ByteString.java:131)
  at okhttp3.n.a (Credentials.java:35)
  at okhttp3.n.a (Credentials.java:30)
  at com.qualaroo.Qualaroo.a (Unknown Source)
  at com.qualaroo.Qualaroo.<init> (Unknown Source)
  at com.qualaroo.Qualaroo.<init> (Unknown Source)
  at com.qualaroo.Qualaroo$Builder.init (Unknown Source)

All the crash report from Android 5.1
Android Studio version : 3.0.1
Build tool version : 27.0.2
compileSdkVersion : 25
targetSdkVersion : 25

**Comment by scana** [comment]
Hey @chapp-hk, thanks for reporting this in.
This problem is related to an issue with Okio library which surfaced recently only on some device with Android 5.1 system.
Take a look here: https://github.com/square/okio/issues/325
You can also take a look here: https://issuetracker.google.com/issues/69364976#comment6

It seems that **temporary fix** for this problem is to make sure to disable D8 compiler, with this line in your `gradle.properties` file:
```
android.enableD8=false
```
You can also take a look here, this is a report of a problem with D8 compiler: https://issuetracker.google.com/issues/69364976

We will release a fix for crashes in our next bugfix release.

EDIT: I just noticed, you guys are using AS 3.0.1 - but this stack trace suggests that you are using D8 compiler - could you check that for me, please?

**Comment by chapp-hk** [comment]
@scana 
yes, we are using D8 compiler
thanks

**Comment by scana** [comment]
Hey @chapp-hk, I hope that disabling D8 compiler has resolved your issue.
We included a workaround for this issue in `1.5.0` to prevent crashing.
